import { FileText, Receipt, Ship, Shield, Landmark, ClipboardList, Cpu, Upload, Anchor } from "lucide-react";

export const DOC_TYPE_LABELS: Record<string, string> = {
  bill_of_lading: "Bill of Lading",
  commercial_invoice: "Commercial Invoice",
  packing_list: "Packing List",
  certificate_of_origin: "Certificate of Origin",
  shipper_letter_of_instruction: "Shipper's Letter of Instruction",
  dock_receipt: "Dock Receipt",
  insurance_certificate: "Insurance Certificate",
  aes_filing: "AES Filing / ITN",
  seaway_bill: "Seaway Bill (SWB)",
  customs_declaration: "Customs Declaration",
  mawb: "Master Air Waybill (MAWB)",
  hawb: "House Air Waybill (HAWB)",
  known_shipper_declaration: "Known Shipper Declaration",
  dg_declaration_air: "Shipper's DG Declaration (IATA)",
  cargo_manifest: "Cargo Manifest",
};

/**
 * Document source classification:
 * - "platform"  → Auto-generated by the platform from shipment data the user provides
 * - "shipper"   → Must be uploaded / provided by the shipper / exporter
 * - "carrier"   → Issued by the shipping line / airline (received, not created)
 */
export type DocSource = "platform" | "shipper" | "carrier";

export const DOC_SOURCE: Record<string, DocSource> = {
  // Platform-generated from user-provided data
  commercial_invoice: "platform",
  packing_list: "platform",
  shipper_letter_of_instruction: "platform",
  aes_filing: "platform",
  dock_receipt: "platform",
  cargo_manifest: "platform",

  // Shipper must provide / upload
  certificate_of_origin: "shipper",
  insurance_certificate: "shipper",
  known_shipper_declaration: "shipper",
  dg_declaration_air: "shipper",
  customs_declaration: "shipper",

  // Carrier-issued documents (shipping line / airline)
  bill_of_lading: "carrier",
  seaway_bill: "carrier",
  mawb: "carrier",
  hawb: "carrier",
};

export const DOC_SOURCE_META: Record<DocSource, { label: string; description: string; icon: typeof FileText }> = {
  platform: {
    label: "Auto-Generated by Platform",
    description: "Created automatically from your shipment data",
    icon: Cpu,
  },
  shipper: {
    label: "Shipper-Provided",
    description: "Upload or provide these documents",
    icon: Upload,
  },
  carrier: {
    label: "Carrier-Issued",
    description: "Received from the shipping line or airline",
    icon: Anchor,
  },
};

export interface DocCategory {
  key: string;
  label: string;
  icon: typeof FileText;
  docTypes: string[];
}

export const DOC_CATEGORIES: DocCategory[] = [
  {
    key: "invoicing",
    label: "Invoicing",
    icon: Receipt,
    docTypes: ["commercial_invoice"],
  },
  {
    key: "bl_waybills",
    label: "BL & Waybills",
    icon: Ship,
    docTypes: ["bill_of_lading", "seaway_bill", "mawb", "hawb"],
  },
  {
    key: "insurance_company",
    label: "Insurance & Company",
    icon: Shield,
    docTypes: ["insurance_certificate", "known_shipper_declaration", "certificate_of_origin", "cargo_manifest"],
  },
  {
    key: "aes_customs",
    label: "AES / Customs",
    icon: Landmark,
    docTypes: ["customs_declaration", "aes_filing", "dg_declaration_air"],
  },
  {
    key: "instructions",
    label: "Shipping Instructions",
    icon: ClipboardList,
    docTypes: ["packing_list", "shipper_letter_of_instruction", "dock_receipt"],
  },
];

export function getDocLabel(docType: string): string {
  return DOC_TYPE_LABELS[docType] || docType.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getCategoryForDocType(docType: string): DocCategory | undefined {
  return DOC_CATEGORIES.find((cat) => cat.docTypes.includes(docType));
}
