
ALTER TABLE public.customs_filings
  ADD COLUMN IF NOT EXISTS filing_option text,
  ADD COLUMN IF NOT EXISTS xtn text,
  ADD COLUMN IF NOT EXISTS usppi_address text,
  ADD COLUMN IF NOT EXISTS usppi_contact_name text,
  ADD COLUMN IF NOT EXISTS usppi_phone text,
  ADD COLUMN IF NOT EXISTS usppi_email text,
  ADD COLUMN IF NOT EXISTS state_of_origin text,
  ADD COLUMN IF NOT EXISTS method_of_transportation text,
  ADD COLUMN IF NOT EXISTS containerized boolean,
  ADD COLUMN IF NOT EXISTS carrier_identification_code text,
  ADD COLUMN IF NOT EXISTS shipment_reference_number text,
  ADD COLUMN IF NOT EXISTS entry_number text,
  ADD COLUMN IF NOT EXISTS hazardous_materials boolean,
  ADD COLUMN IF NOT EXISTS in_bond_code text,
  ADD COLUMN IF NOT EXISTS routed_export_transaction boolean,
  ADD COLUMN IF NOT EXISTS ultimate_consignee_type text,
  ADD COLUMN IF NOT EXISTS authorized_agent_name text,
  ADD COLUMN IF NOT EXISTS authorized_agent_address text,
  ADD COLUMN IF NOT EXISTS authorized_agent_ein text,
  ADD COLUMN IF NOT EXISTS original_itn text,
  ADD COLUMN IF NOT EXISTS related_parties boolean,
  ADD COLUMN IF NOT EXISTS loading_pier text,
  ADD COLUMN IF NOT EXISTS eei_exemption_citation text,
  ADD COLUMN IF NOT EXISTS forwarder_authorization_language text,
  ADD COLUMN IF NOT EXISTS shipper_certification_language text,
  ADD COLUMN IF NOT EXISTS title_of_shipper_representative text;
